# Generated by Django 5.2.1 on 2025-05-15 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la ligue')),
                ('country', models.CharField(max_length=100, verbose_name='Pays')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='leagues_logos/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Ligue',
                'verbose_name_plural': 'Ligues',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name="Nom de l'équipe")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams_logos/', verbose_name='Logo')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('founded_year', models.IntegerField(blank=True, null=True, verbose_name='Année de fondation')),
                ('stadium', models.CharField(blank=True, max_length=100, verbose_name='Stade')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teams.league', verbose_name='Ligue')),
            ],
            options={
                'verbose_name': 'Équipe',
                'verbose_name_plural': 'Équipes',
                'ordering': ['name'],
            },
        ),
    ]
