# Generated by Django 5.2.1 on 2025-05-15 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date et heure')),
                ('home_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Score domicile')),
                ('away_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Score extérieur')),
                ('status', models.CharField(choices=[('scheduled', 'À venir'), ('live', 'En cours'), ('completed', 'Terminé'), ('postponed', 'Reporté'), ('canceled', 'Annulé')], default='scheduled', max_length=20, verbose_name='Statut')),
                ('result', models.CharField(choices=[('home_win', 'Victoire domicile'), ('away_win', 'Victoire extérieur'), ('draw', 'Match nul'), ('pending', 'En attente')], default='pending', max_length=20, verbose_name='Résultat')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='teams.team', verbose_name='Équipe extérieur')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='teams.team', verbose_name='Équipe domicile')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matchs',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.CharField(choices=[('home_win', 'Victoire domicile'), ('away_win', 'Victoire extérieur'), ('draw', 'Match nul')], max_length=20, verbose_name='Type de pari')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('odds_value', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Valeur de la cote')),
                ('potential_win', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gain potentiel')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('won', 'Gagné'), ('lost', 'Perdu'), ('canceled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='teams.match', verbose_name='Match')),
            ],
            options={
                'verbose_name': 'Pari',
                'verbose_name_plural': 'Paris',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Matchday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Numéro de journée')),
                ('date', models.DateField(verbose_name='Date')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Journée terminée')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchdays', to='teams.league', verbose_name='Ligue')),
            ],
            options={
                'verbose_name': 'Journée',
                'verbose_name_plural': 'Journées',
                'ordering': ['league', 'number'],
                'unique_together': {('league', 'number')},
            },
        ),
        migrations.AddField(
            model_name='match',
            name='matchday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='teams.matchday', verbose_name='Journée'),
        ),
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_win', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Cote victoire domicile')),
                ('draw', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Cote match nul')),
                ('away_win', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Cote victoire extérieur')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='teams.match', verbose_name='Match')),
            ],
            options={
                'verbose_name': 'Cote',
                'verbose_name_plural': 'Cotes',
            },
        ),
    ]
