# Generated by Django 5.2.1 on 2025-05-15 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_update_historical_matches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bet',
            options={},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={},
        ),
        migrations.RemoveField(
            model_name='bet',
            name='odds_value',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='potential_win',
        ),
        migrations.RemoveField(
            model_name='match',
            name='result',
        ),
        migrations.AddField(
            model_name='bet',
            name='odds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='match',
            name='stadium',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bet',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bet',
            name='bet_type',
            field=models.CharField(choices=[('home_win', 'Victoire domicile'), ('draw', 'Match nul'), ('away_win', 'Victoire extérieur')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='teams.match'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('won', 'Gagné'), ('lost', 'Perdu')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='matchday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='teams.matchday'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programmé'), ('live', 'En cours'), ('completed', 'Terminé')], default='scheduled', max_length=20),
        ),
    ]
