# Generated by Django 5.2.1 on 2025-05-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='Solde'),
        ),
    ]
