# Generated by Django 5.2.1 on 2025-05-15 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_solde'),
        ('accounts', '0002_utilisateur_balance'),
    ]

    operations = [
    ]
