# Generated by Django 5.2.1 on 2025-05-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_0002_remove_solde_0002_utilisateur_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10, verbose_name='Solde'),
        ),
    ]
